FROM ubuntu:18.04
RUN apt update && apt install -y git wget unzip python3-pip
RUN pip3 install --user imageio imageio-ffmpeg dataclasses pyyaml stable-baselines3 torch tensorboard optuna
RUN wget https://github.com/axelbr/racecar_gym/releases/download/tracks-v1.0.0/all.zip
RUN git clone https://github.com/axelbr/racecar_gym.git
RUN pip3 install --user -e racecar_gym/
RUN mv all.zip racecar_gym/models/scenes/ && cd racecar_gym/models/scenes/ && unzip all.zip
WORKDIR /app
COPY . .