learning_rate: 0.0003
policy_kwargs: {
  net_arch: [400, {pi: [400, 400, 400], vf: [400, 400]}]
}
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
#clip_range_vf: Optional[float] = None
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: False
sde_sample_freq: -1
#target_kl: Optional[float] = None
