version: '2.3'
services:
  database:
    image: mysql:5.7
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${STUDY}
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    network_mode: host
    volumes:
      - mysql_volume:/var/lib/mysql

  tuning:
    image: tuwcps/racing:${LABEL}
    command: bash -c "
        python run_tuning.py
            --study_name ${STUDY}
            --agent ${AGENT}
            --track ${TRACK}
            --task max_progress
            --tunable_params hyperparams/tuning/${AGENT}.yml
            --default_params hyperparams/default/${AGENT}.yml
            --steps ${STEPS}
            --epochs ${EPOCHS}
            --trials ${TRIALS}
            --logdir /app/$STUDY/
            --storage mysql+pymysql://user:password@localhost/${STUDY}
        "
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - ${LOGDIR}:/app/$STUDY/

volumes:
  mysql_volume: